app/control_recipe/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField
from wtforms.validators import DataRequired


class ControlRecipeForm(FlaskForm):

  # Form for admin to add or edit a department
  control = SelectField("Control", coerce=int)
  recipe = SelectField("Recipe", coerce=int)
  submit = SubmitField("Submit")

app/control_recipe/__init__.py
from flask import Blueprint

control_recipe = Blueprint('control_recipe', __name__)

from . import views

app/control_recipe/views.py
from flask import abort, flash, redirect, render_template, url_for
from sqlalchemy import text
from flask_login import login_required

from . import control_recipe
from .forms import ControlRecipeForm
from .. import db
from ..models import control as controldbo
from ..models import recipe as recipedbo
from ..models import control_recipe as controlrecipedbo
from ..helpers import confirm_user_is_admin


@control_recipe.route('/control_recipes', methods=['GET', 'POST'])
@login_required
def list_control_recipes():
  
  confirm_user_is_admin()
  
  # List all recipes
  sql = text("select cr.control_recipe_id, c.control_id, c.control_name, " +
                     " r.recipe_id, r.recipe_name " +
             "from mc_demo.control_recipe cr " +
             "inner join mc_demo.control c " +
             "  on cr.control_id = c.control_id " +
             "inner join mc_demo.recipe r " +
             "  on cr.recipe_id = r.recipe_id ")
  crlist = db.engine.execute(sql)

  return render_template("recipe/recipe_crud.html",
                         controlrecipes=crlist, title="Control Recipes")


@control_recipe.route('/control_recipes/add/<int:rid>/<int:cid>', methods=['GET', 'POST'])
@login_required
def add_control_recipe(rid, cid):
  
  confirm_user_is_admin()
  
  # Add a control recipe to the database
  
  add_control_recipe = True
  
  form = ControlRecipeForm()
  """   if form.is_submitted:
    print("Submitted")
  if form.validate():
    print("VALID ONE")
  print(form.errors)
  if form.validate_on_submit():
    print("VALID") """
  crdata = controlrecipedbo(control_id=cid, #form.control_id.data,
                            recipe_id=rid) #form.recipe_id.data)
  try:
    # add control recipe to the database
    db.session.add(crdata)
    db.session.commit()
    flash('You have successfully added a new control recipe.')
  except:
    # in case control recipe id already exists
    flash('Error: control recipe already exists.')
  
  # redirect to controls page
  return redirect(url_for('control_recipe.list_control_recipes'))

  # load control template
  # return render_template('recipe/recipe_crud.html', action="Add",
  #                       add_control_recipe=add_control_recipe, form=form,
  #                       title="Add Control Recipe")


@control_recipe.route('/control_recipes/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_control_recipe(id):

  confirm_user_is_admin()

  # Edit a control recipe
  add_control_recipe = False

  crdata = controlrecipedbo.query.get_or_404(id)
  form = ControlRecipeForm(obj=crdata)
  # Load choices
  form.control.choices = [(c.control_id, c.control_name) for c in controldbo.query.order_by("control_name")]
  form.recipe.choices = [(r.recipe_id, r.recipe_name) for r in recipedbo.query.order_by("recipe_name")]
  if form.validate_on_submit():
    crdata.control_id = form.control.data
    crdata.recipe_id = form.recipe.data
    db.session.commit()
    flash('You have successfully edited the control.')

    # redirect to the control recipes page
    return redirect(url_for('control_recipe.list_control_recipes'))

  form.control.data = crdata.control_id
  form.recipe.data = crdata.recipe_id
  return render_template('control_recipe/control_recipe.html', action="Edit",
                          add_control_recipe=add_control_recipe, form=form,
                          control=crdata, title="Edit Control Recipe")


@control_recipe.route('/control_recipes/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_control_recipe(id):

  confirm_user_is_admin()

  # Delete a control recipe from the database

  crdata = controlrecipedbo.query.get_or_404(id)
  db.session.delete(crdata)
  db.session.commit()
  flash('You have successfully deleted the control recipe.')

  # redirect to the control recipes page
  return redirect(url_for('control_recipe.list_control_recipes'))

  return render_template(title="Delete control recipe")

app/templates/control_recipe/control_recipe.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    {% if add_control_recipe %}
        Add Control Recipe
    {% else %}
        Edit Control Recipe
    {% endif %}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_control_recipe %}
                <h1>Add Control Recipe</h1>
            {% else %}
                <h1>Edit Control Recipe</h1>
            {% endif %}
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/control_recipe/control_recipes.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Control Recipes{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Control Recipes</h1>
        {% if controlrecipes %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="15%"> Control Name </th>
                  <th width="40%"> Recipe Name </th>
                  <th width="15%"> Edit </th>
                  <th width="15%"> Delete </th>
                </tr>
              </thead>
              <tbody>
              {% for cr in controlrecipes %}
                <tr>
                  <td> {{ cr.control_name }} </td>
                  <td> {{ cr.recipe_name }} </td>
                  <td>
                    <a href="{{ url_for('control_recipe.edit_control_recipe', id=cr.control_recipe_id) }}">
                      <i class="fa fa-pencil"></i> Edit
                    </a>
                  </td>
                  <td>
                    <a href="{{ url_for('control_recipe.delete_control_recipe', id=cr.control_recipe_id) }}">
                      <i class="fa fa-trash"></i> Delete
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No control recipes have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('control_recipe.add_control_recipe') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Recipe
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}